 

// -----------------------------------------------------------------------
// <autogenerated>
//    This code was generated from a template.
//
//    Changes to this file may cause incorrect behaviour and will be lost
//    if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using BrightstarDB.Client;
using BrightstarDB.EntityFramework;


namespace BrightstarDB.ConcurrencyIssue 
{
    public partial class Context1 : BrightstarEntityContext {
    	
    	static Context1() 
    	{
            InitializeEntityMappingStore();
        }
        
        /// <summary>
        /// Initialize the internal cache of entity attribute information.
        /// </summary>
        /// <remarks>
        /// This method is normally invoked from the static constructor for the generated context class.
        /// It is provided as a public static method to enable the use of the cached entity attribute 
        /// information without the need to construct a context (typically in test code). 
        /// In normal application code you should never need to explicitly call this method.
        /// </remarks>
        public static void InitializeEntityMappingStore()
        {
    		var provider = new ReflectionMappingProvider();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.ConcurrencyIssue.IEntity));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.ConcurrencyIssue.IEntity, BrightstarDB.ConcurrencyIssue.Entity>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.ConcurrencyIssue.ISimpleEntity));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.ConcurrencyIssue.ISimpleEntity, BrightstarDB.ConcurrencyIssue.SimpleEntity>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.ConcurrencyIssue.IComplexEntity1));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.ConcurrencyIssue.IComplexEntity1, BrightstarDB.ConcurrencyIssue.ComplexEntity1>();
    		provider.AddMappingsForType(EntityMappingStore.Instance, typeof(BrightstarDB.ConcurrencyIssue.IComplexEntity2));
    		EntityMappingStore.Instance.SetImplMapping<BrightstarDB.ConcurrencyIssue.IComplexEntity2, BrightstarDB.ConcurrencyIssue.ComplexEntity2>();
    	}
    	
    	/// <summary>
    	/// Initialize a new entity context using the specified BrightstarDB
    	/// Data Object Store connection
    	/// </summary>
    	/// <param name="dataObjectStore">The connection to the BrightstarDB Data Object Store that will provide the entity objects</param>
    	public Context1(IDataObjectStore dataObjectStore) : base(dataObjectStore)
    	{
    		InitializeContext();
    	}
    
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar connection string
    	/// </summary>
    	/// <param name="connectionString">The connection to be used to connect to an existing BrightstarDB store</param>
    	/// <param name="enableOptimisticLocking">OPTIONAL: If set to true optmistic locking will be applied to all entity updates</param>
        /// <param name="updateGraphUri">OPTIONAL: The URI identifier of the graph to be updated with any new triples created by operations on the store. If
        /// not defined, the default graph in the store will be updated.</param>
        /// <param name="datasetGraphUris">OPTIONAL: The URI identifiers of the graphs that will be queried to retrieve entities and their properties.
        /// If not defined, all graphs in the store will be queried.</param>
        /// <param name="versionGraphUri">OPTIONAL: The URI identifier of the graph that contains version number statements for entities. 
        /// If not defined, the <paramref name="updateGraphUri"/> will be used.</param>
    	public Context1(
    	    string connectionString, 
    		bool? enableOptimisticLocking=null,
    		string updateGraphUri = null,
    		IEnumerable<string> datasetGraphUris = null,
    		string versionGraphUri = null
        ) : base(connectionString, enableOptimisticLocking, updateGraphUri, datasetGraphUris, versionGraphUri)
    	{
    		InitializeContext();
    	}
    
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar
    	/// connection string retrieved from the configuration.
    	/// </summary>
    	public Context1() : base()
    	{
    		InitializeContext();
    	}
    	
    	/// <summary>
    	/// Initialize a new entity context using the specified Brightstar
    	/// connection string retrieved from the configuration and the
    	//  specified target graphs
    	/// </summary>
        /// <param name="updateGraphUri">The URI identifier of the graph to be updated with any new triples created by operations on the store. If
        /// set to null, the default graph in the store will be updated.</param>
        /// <param name="datasetGraphUris">The URI identifiers of the graphs that will be queried to retrieve entities and their properties.
        /// If set to null, all graphs in the store will be queried.</param>
        /// <param name="versionGraphUri">The URI identifier of the graph that contains version number statements for entities. 
        /// If set to null, the value of <paramref name="updateGraphUri"/> will be used.</param>
    	public Context1(
    		string updateGraphUri,
    		IEnumerable<string> datasetGraphUris,
    		string versionGraphUri
    	) : base(updateGraphUri:updateGraphUri, datasetGraphUris:datasetGraphUris, versionGraphUri:versionGraphUri)
    	{
    		InitializeContext();
    	}
    	
    	private void InitializeContext() 
    	{
    		Entities = 	new BrightstarEntitySet<BrightstarDB.ConcurrencyIssue.IEntity>(this);
    		SimpleEntities = 	new BrightstarEntitySet<BrightstarDB.ConcurrencyIssue.ISimpleEntity>(this);
    		ComplexEntity1s = 	new BrightstarEntitySet<BrightstarDB.ConcurrencyIssue.IComplexEntity1>(this);
    		ComplexEntity2s = 	new BrightstarEntitySet<BrightstarDB.ConcurrencyIssue.IComplexEntity2>(this);
    	}
    	
    	public IEntitySet<BrightstarDB.ConcurrencyIssue.IEntity> Entities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.ConcurrencyIssue.ISimpleEntity> SimpleEntities
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.ConcurrencyIssue.IComplexEntity1> ComplexEntity1s
    	{
    		get; private set;
    	}
    	
    	public IEntitySet<BrightstarDB.ConcurrencyIssue.IComplexEntity2> ComplexEntity2s
    	{
    		get; private set;
    	}
    	
        public IEntitySet<T> EntitySet<T>() where T : class {
            var itemType = typeof(T);
            if (typeof(T).Equals(typeof(BrightstarDB.ConcurrencyIssue.IEntity))) {
                return (IEntitySet<T>)this.Entities;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.ConcurrencyIssue.ISimpleEntity))) {
                return (IEntitySet<T>)this.SimpleEntities;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.ConcurrencyIssue.IComplexEntity1))) {
                return (IEntitySet<T>)this.ComplexEntity1s;
            }
            if (typeof(T).Equals(typeof(BrightstarDB.ConcurrencyIssue.IComplexEntity2))) {
                return (IEntitySet<T>)this.ComplexEntity2s;
            }
            throw new InvalidOperationException(typeof(T).FullName + " is not a recognized entity interface type.");
        }
    
        } // end class Context1
        
}
namespace BrightstarDB.ConcurrencyIssue 
{
    
    public partial class Entity : BrightstarEntityObject, IEntity 
    {
    	public Entity(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public Entity(BrightstarEntityContext context) : base(context, typeof(Entity)) { }
    	public Entity() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.ConcurrencyIssue.IEntity
    	#endregion
    }
}
namespace BrightstarDB.ConcurrencyIssue 
{
    
    public partial class SimpleEntity : BrightstarEntityObject, ISimpleEntity 
    {
    	public SimpleEntity(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public SimpleEntity(BrightstarEntityContext context) : base(context, typeof(SimpleEntity)) { }
    	public SimpleEntity() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.ConcurrencyIssue.ISimpleEntity
    
    	public System.String Identifier
    	{
            		get { return GetRelatedProperty<System.String>("Identifier"); }
            		set { SetRelatedProperty("Identifier", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.ConcurrencyIssue.IEntity
    	#endregion
    }
}
namespace BrightstarDB.ConcurrencyIssue 
{
    
    public partial class ComplexEntity1 : BrightstarEntityObject, IComplexEntity1 
    {
    	public ComplexEntity1(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public ComplexEntity1(BrightstarEntityContext context) : base(context, typeof(ComplexEntity1)) { }
    	public ComplexEntity1() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.ConcurrencyIssue.IComplexEntity1
    
    	public System.Int32 Counter
    	{
            		get { return GetRelatedProperty<System.Int32>("Counter"); }
            		set { SetRelatedProperty("Counter", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.ConcurrencyIssue.IEntity
    	#endregion
    }
}
namespace BrightstarDB.ConcurrencyIssue 
{
    
    public partial class ComplexEntity2 : BrightstarEntityObject, IComplexEntity2 
    {
    	public ComplexEntity2(BrightstarEntityContext context, BrightstarDB.Client.IDataObject dataObject) : base(context, dataObject) { }
        public ComplexEntity2(BrightstarEntityContext context) : base(context, typeof(ComplexEntity2)) { }
    	public ComplexEntity2() : base() { }
    	public System.String Id { get {return GetKey(); } set { SetKey(value); } }
    	#region Implementation of BrightstarDB.ConcurrencyIssue.IComplexEntity2
    
    	public System.String Name
    	{
            		get { return GetRelatedProperty<System.String>("Name"); }
            		set { SetRelatedProperty("Name", value); }
    	}
    	#endregion
    	#region Implementation of BrightstarDB.ConcurrencyIssue.IEntity
    	#endregion
    }
}
